# Generated by Django 5.1.7 on 2025-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
            ],
        ),
    ]
